name: CI Build
on: [push, pull_request]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 8
      - uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: lang/java/gradle-plugin
          gradle-executable: lang/java/gradle-plugin/gradlew
          arguments: build
